import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Alert, AlertDescription } from './ui/alert';
import { 
  FileText, 
  CheckCircle, 
  AlertTriangle,
  Target,
  Clock,
  UserCheck,
  Eye,
  RefreshCw,
  ThumbsUp,
  ThumbsDown,
  Info,
  Loader2,
  Sparkles
} from 'lucide-react';

interface OverviewData {
  scope: string | null;
  objective: string | null;
  quality_criteria: string[];
  examples: {
    positive: Array<{
      description: string;
      image_reference: string | null;
    }>;
    negative: Array<{
      description: string;
      image_reference: string | null;
    }>;
    general: Array<{
      description: string;
      image_reference: string | null;
    }>;
  };
  edge_cases: Array<{
    case: string;
    handling: string | null;
    source: 'extracted' | 'inferred';
  }>;
  annotator_responsibilities: string[];
  expected_throughput: string | null;
}

interface Props {
  sessionId: string | null;
  isActive: boolean;            
  onSummaryComplete?: () => void;
}

export function GuidelineSummary({ sessionId, isActive, onSummaryComplete }: Props) {
  const [overview, setOverview] = useState<OverviewData | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [error, setError] = useState<string | null>(null);

  
  useEffect(() => {
    if (sessionId) {
      fetchOverview();
    }
  }, [sessionId]);

  useEffect(() => {
    if (isActive && sessionId && !hasAutoGenerated && !overview && !loading && !generating) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [isActive, sessionId, hasAutoGenerated, overview, loading, generating]);

  const fetchOverview = async () => {
    if (!sessionId) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(`/api/overview/${sessionId}`);
      const data = await response.json();
      
      if (data.overview) {
        setOverview(data.overview);
        if (onSummaryComplete) {
          onSummaryComplete();
        }
      } else {
        setError(null); // Don't show error if just not generated yet
      }
    } catch (err) {
      console.error("Failed to fetch overview:", err);
      setError("Failed to fetch overview");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    if (!sessionId) return;
    
    setGenerating(true);
    setError(null);
    
    try {
      const response = await fetch(`/api/overview/${sessionId}/generate`, {
        method: 'POST'
      });
      
      if (!response.ok) {
        throw new Error('Failed to generate overview');
      }
      
      const data = await response.json();
      
      if (data.overview) {
        setOverview(data.overview);
        if (onSummaryComplete) {
          onSummaryComplete();
        }
      }
    } catch (err) {
      console.error("Failed to generate overview:", err);
      setError("Failed to generate overview. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  // Loading state
  if (loading) {
    return (
      <Card>
        <CardContent className="py-12">
          <div className="flex flex-col items-center justify-center space-y-4">
            <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
            <p className="text-gray-600">Loading overview...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Not generated state
  if (!overview) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Sparkles className="w-5 h-5 text-blue-600" />
            <span>Guideline Overview</span>
          </CardTitle>
          <CardDescription>
            Generate a comprehensive overview of annotation guidelines including scope, objectives, quality criteria, and more
          </CardDescription>
        </CardHeader>
        <CardContent className="py-8">
          <div className="text-center space-y-4">
            <div className="flex justify-center">
              <div className="p-4 bg-blue-50 rounded-full">
                <FileText className="w-12 h-12 text-blue-600" />
              </div>
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">No Overview Generated Yet</h3>
              <p className="text-gray-600 mb-4">
                Click the button below to extract overview information from your uploaded guidelines
              </p>
            </div>
            <Button 
              onClick={handleGenerate} 
              disabled={!sessionId || generating}
              size="lg"
            >
              {generating ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating Overview...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Generate Overview
                </>
              )}
            </Button>
            {error && (
              <Alert variant="destructive" className="mt-4">
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
          </div>
        </CardContent>
      </Card>
    );
  }

  // Main overview display
  return (
    <div className="space-y-6">
      {/* Header with Actions */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold flex items-center space-x-2">
            <FileText className="w-6 h-6 text-blue-600" />
            <span>Guideline Overview</span>
          </h2>
          <p className="text-gray-600 mt-1">Comprehensive summary of annotation guidelines</p>
        </div>
        <Button 
          onClick={handleGenerate} 
          disabled={generating}
          variant="outline"
        >
          {generating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Regenerating...
            </>
          ) : (
            <>
              <RefreshCw className="w-4 h-4 mr-2" />
              Regenerate
            </>
          )}
        </Button>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {/* Scope & Objective */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Target className="w-5 h-5 text-blue-600" />
              <span>Scope</span>
            </CardTitle>
            <CardDescription>What is included/excluded from annotation</CardDescription>
          </CardHeader>
          <CardContent>
            {overview.scope ? (
              <p className="text-gray-700 leading-relaxed">{overview.scope}</p>
            ) : (
              <p className="text-gray-400 italic">No scope information available</p>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <FileText className="w-5 h-5 text-purple-600" />
              <span>Objective</span>
            </CardTitle>
            <CardDescription>Purpose and goals of the annotation task</CardDescription>
          </CardHeader>
          <CardContent>
            {overview.objective ? (
              <p className="text-gray-700 leading-relaxed">{overview.objective}</p>
            ) : (
              <p className="text-gray-400 italic">No objective information available</p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Quality Criteria */}
      {overview.quality_criteria && overview.quality_criteria.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <CheckCircle className="w-5 h-5 text-green-600" />
              <span>Quality Criteria</span>
            </CardTitle>
            <CardDescription>
              Standards that annotations must meet for quality assurance
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {overview.quality_criteria.map((criterion, idx) => (
                <li key={idx} className="flex items-start space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700 leading-relaxed">{criterion}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Examples */}
      {(overview.examples.positive.length > 0 || 
        overview.examples.negative.length > 0 || 
        overview.examples.general.length > 0) && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Eye className="w-5 h-5 text-blue-600" />
              <span>Examples</span>
            </CardTitle>
            <CardDescription>
              Practical examples demonstrating correct application of annotation guidelines
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Positive Examples */}
            {overview.examples.positive.length > 0 && (
              <div>
                <h4 className="font-semibold text-green-600 mb-3 flex items-center space-x-2">
                  <ThumbsUp className="w-5 h-5" />
                  <span>Correct Examples</span>
                </h4>
                <div className="space-y-3">
                  {overview.examples.positive.map((ex, idx) => (
                    <div key={idx} className="p-4 border border-green-200 bg-green-50 rounded-lg">
                      <div className="flex items-start space-x-3">
                        <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
                        <div className="flex-1">
                          <p className="text-gray-700 leading-relaxed">{ex.description}</p>
                          {ex.image_reference && (
                            <Badge variant="outline" className="mt-2">
                              <Eye className="w-3 h-3 mr-1" />
                              Contains Image
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Negative Examples */}
            {overview.examples.negative.length > 0 && (
              <div>
                <h4 className="font-semibold text-red-600 mb-3 flex items-center space-x-2">
                  <ThumbsDown className="w-5 h-5" />
                  <span>Incorrect Examples</span>
                </h4>
                <div className="space-y-3">
                  {overview.examples.negative.map((ex, idx) => (
                    <div key={idx} className="p-4 border border-red-200 bg-red-50 rounded-lg">
                      <div className="flex items-start space-x-3">
                        <AlertTriangle className="w-5 h-5 text-red-600 mt-0.5 flex-shrink-0" />
                        <div className="flex-1">
                          <p className="text-gray-700 leading-relaxed">{ex.description}</p>
                          {ex.image_reference && (
                            <Badge variant="outline" className="mt-2">
                              <Eye className="w-3 h-3 mr-1" />
                              Contains Image
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* General Examples */}
            {overview.examples.general.length > 0 && (
              <div>
                <h4 className="font-semibold text-blue-600 mb-3 flex items-center space-x-2">
                  <Info className="w-5 h-5" />
                  <span>General Examples</span>
                </h4>
                <div className="space-y-3">
                  {overview.examples.general.map((ex, idx) => (
                    <div key={idx} className="p-4 border border-blue-200 bg-blue-50 rounded-lg">
                      <div className="flex items-start space-x-3">
                        <Info className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
                        <div className="flex-1">
                          <p className="text-gray-700 leading-relaxed">{ex.description}</p>
                          {ex.image_reference && (
                            <Badge variant="outline" className="mt-2">
                              <Eye className="w-3 h-3 mr-1" />
                              Contains Image
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Edge Cases */}
      {overview.edge_cases && overview.edge_cases.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <AlertTriangle className="w-5 h-5 text-orange-600" />
              <span>Edge Cases</span>
            </CardTitle>
            <CardDescription>
              Handling challenging scenarios and ambiguous situations in annotation
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {overview.edge_cases.map((edge, idx) => {
              const borderColors = [
                'border-l-yellow-500',
                'border-l-orange-500', 
                'border-l-red-500',
                'border-l-purple-500',
                'border-l-blue-500',
                'border-l-gray-500'
              ];
              const iconColors = [
                'text-yellow-600',
                'text-orange-600',
                'text-red-600',
                'text-purple-600',
                'text-blue-600',
                'text-gray-600'
              ];
              
              const borderColor = borderColors[idx % borderColors.length];
              const iconColor = iconColors[idx % iconColors.length];
              
              return (
                <div key={idx} className={`p-4 border-l-4 ${borderColor} rounded-r-lg bg-gray-50`}>
                  <div className="flex items-start space-x-3">
                    <AlertTriangle className={`w-5 h-5 ${iconColor} mt-1 flex-shrink-0`} />
                    <div className="flex-1">
                      <div className="flex items-start justify-between mb-2">
                        <h4 className="font-semibold text-gray-900">{edge.case}</h4>
                        <Badge variant={edge.source === 'extracted' ? 'default' : 'secondary'} className="ml-2">
                          {edge.source}
                        </Badge>
                      </div>
                      {edge.handling && (
                        <p className="text-gray-700 leading-relaxed">
                          <strong className="text-gray-900">Approach:</strong> {edge.handling}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>
      )}

      {/* Annotator Responsibilities */}
      {overview.annotator_responsibilities && overview.annotator_responsibilities.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <UserCheck className="w-5 h-5 text-purple-600" />
              <span>Annotator Tasks</span>
            </CardTitle>
            <CardDescription>
              Key accountability areas and obligations for annotation quality assurance
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3 list-none">
              {overview.annotator_responsibilities.map((resp, idx) => {
                const colors = [
                  'text-blue-600',
                  'text-green-600',
                  'text-purple-600',
                  'text-orange-600',
                  'text-red-600',
                  'text-yellow-600',
                  'text-indigo-600',
                  'text-teal-600'
                ];
                const color = colors[idx % colors.length];
                
                return (
                  <li key={idx} className="flex items-start space-x-3">
                    <CheckCircle className={`w-5 h-5 ${color} mt-0.5 flex-shrink-0`} />
                    <span className="text-gray-700 leading-relaxed">{resp}</span>
                  </li>
                );
              })}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Expected Throughput */}
      {overview.expected_throughput && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Clock className="w-5 h-5 text-blue-600" />
              <span>Expected TPT (Time Per Task)</span>
            </CardTitle>
            <CardDescription>
              Estimated time requirements and productivity expectations
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-gray-900 text-lg font-medium">{overview.expected_throughput}</p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}